version: "3.8"

services:
  app:
    image: coaching-hub-backend:15.0.0
    container_name: coaching-hub-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appdb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_STORAGE_UPLOAD_DIR: /var/www/coaching-hub/uploads

    volumes:
      - /var/www/coaching-hub/uploads:/var/www/coaching-hub/uploads
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
