INSERT INTO nationality (code, name_en, name_ar, deleted, active) VALUES
('AF', 'Afghan', 'أفغاني', false, true),
('AL', 'Albanian', 'ألباني', false, true),
('DZ', 'Algerian', 'جزائري', false, true),
('AS', 'American Samoan', 'سامواي أمريكي', false, true),
('AD', 'Andorran', 'أندوري', false, true),
('AO', 'Angolan', 'أنغولي', false, true),
('AI', 'Anguillan', 'أنغويلي', false, true),
('AQ', 'Antarctican', 'أنتاركتيكي', false, true),
('AG', 'Antiguan and Barbudan', 'أنتيغوي وبربودي', false, true),
('AR', 'Argentine', 'أرجنتيني', false, true),
('AM', 'Armenian', 'أرميني', false, true),
('AW', 'Aruban', 'أروبي', false, true),
('AU', 'Australian', 'أسترالي', false, true),
('AT', 'Austrian', 'نمساوي', false, true),
('AZ', 'Azerbaijani', 'أذربيجاني', false, true),
('BS', 'Bahamian', 'باهامي', false, true),
('BH', 'Bahraini', 'بحريني', false, true),
('BD', 'Bangladeshi', 'بنغلاديشي', false, true),
('BB', 'Barbadian', 'باربادوسي', false, true),
('BY', 'Belarusian', 'بيلاروسي', false, true),
('BE', 'Belgian', 'بلجيكي', false, true),
('BZ', 'Belizean', 'بليزي', false, true),
('BJ', 'Beninese', 'بنيني', false, true),
('BM', 'Bermudian', 'برمودي', false, true),
('BT', 'Bhutanese', 'بوتاني', false, true),
('BO', 'Bolivian', 'بوليفي', false, true),
('BA', 'Bosnian and Herzegovinian', 'بوسني وهرسكي', false, true),
('BW', 'Botswanan', 'بوتسواني', false, true),
('BR', 'Brazilian', 'برازيلي', false, true),
('BN', 'Bruneian', 'بروناوي', false, true),
('BG', 'Bulgarian', 'بلغاري', false, true),
('BF', 'Burkinabe', 'بوركينابي', false, true),
('BI', 'Burundian', 'بوروندي', false, true),
('KH', 'Cambodian', 'كمبودي', false, true),
('CM', 'Cameroonian', 'كاميروني', false, true),
('CA', 'Canadian', 'كندي', false, true),
('CV', 'Cape Verdean', 'رأسي أخضري', false, true),
('KY', 'Caymanian', 'كايماني', false, true),
('CF', 'Central African', 'أفريقي وسطي', false, true),
('TD', 'Chadian', 'تشادي', false, true),
('CL', 'Chilean', 'تشيلي', false, true),
('CN', 'Chinese', 'صيني', false, true),
('CX', 'Christmas Islander', 'من جزيرة الكريسماس', false, true),
('CC', 'Cocos Islander', 'من جزر كوكوس', false, true),
('CO', 'Colombian', 'كولومبي', false, true),
('KM', 'Comorian', 'قمري', false, true),
('CG', 'Congolese', 'كونغولي', false, true),
('CD', 'Congolese', 'كونغولي ديمقراطي', false, true),
('CK', 'Cook Islander', 'من جزر كوك', false, true),
('CR', 'Costa Rican', 'كوستاريكي', false, true),
('CI', 'Ivorian', 'إيفواري', false, true),
('HR', 'Croatian', 'كرواتي', false, true),
('CU', 'Cuban', 'كوبي', false, true),
('CY', 'Cypriot', 'قبرصي', false, true),
('CZ', 'Czech', 'تشيكي', false, true),
('DK', 'Danish', 'دنماركي', false, true),
('DJ', 'Djiboutian', 'جيبوتي', false, true),
('DM', 'Dominican', 'دومينيكي', false, true),
('DO', 'Dominican', 'دومينيكاني', false, true),
('EC', 'Ecuadorian', 'إكوادوري', false, true),
('EG', 'Egyptian', 'مصري', false, true),
('SV', 'Salvadoran', 'سلفادوري', false, true),
('GQ', 'Equatorial Guinean', 'غيني استوائي', false, true),
('ER', 'Eritrean', 'إريتري', false, true),
('EE', 'Estonian', 'إستوني', false, true),
('SZ', 'Swazi', 'إسواتيني', false, true),
('ET', 'Ethiopian', 'إثيوبي', false, true),
('FK', 'Falkland Islander', 'فوكلاندي', false, true),
('FO', 'Faroese', 'فروي', false, true),
('FJ', 'Fijian', 'فيجي', false, true),
('FI', 'Finnish', 'فنلندي', false, true),
('FR', 'French', 'فرنسي', false, true),
('GF', 'French Guianese', 'غياني فرنسي', false, true),
('PF', 'French Polynesian', 'بولينيزي فرنسي', false, true),
('TF', 'French Southern Territories', 'من الأقاليم الجنوبية الفرنسية', false, true),
('GA', 'Gabonese', 'غابوني', false, true),
('GM', 'Gambian', 'غامبي', false, true),
('GE', 'Georgian', 'جورجي', false, true),
('DE', 'German', 'ألماني', false, true),
('GH', 'Ghanaian', 'غاني', false, true),
('GI', 'Gibraltarian', 'جبل طارقي', false, true),
('GR', 'Greek', 'يوناني', false, true),
('GL', 'Greenlandic', 'غرينلاندي', false, true),
('GD', 'Grenadian', 'غرينادي', false, true),
('GP', 'Guadeloupean', 'غوادلوبي', false, true),
('GU', 'Guamanian', 'غوامي', false, true),
('GT', 'Guatemalan', 'غواتيمالي', false, true),
('GG', 'Guernsey', 'غيرنزي', false, true),
('GN', 'Guinean', 'غيني', false, true),
('GW', 'Bissau-Guinean', 'غيني بيساوي', false, true),
('GY', 'Guyanese', 'غياني', false, true),
('HT', 'Haitian', 'هايتي', false, true),
('HM', 'Heard and McDonald Islands', 'من جزر هيرد وماكدونالد', false, true),
('VA', 'Vatican', 'فاتيكاني', false, true),
('HN', 'Honduran', 'هندوراسي', false, true),
('HK', 'Hong Konger', 'هونغ كونغي', false, true),
('HU', 'Hungarian', 'مجري', false, true),
('IS', 'Icelander', 'آيسلندي', false, true),
('IN', 'Indian', 'هندي', false, true),
('ID', 'Indonesian', 'إندونيسي', false, true),
('IR', 'Iranian', 'إيراني', false, true),
('IQ', 'Iraqi', 'عراقي', false, true),
('IE', 'Irish', 'أيرلندي', false, true),
('IL', 'Israeli', 'إسرائيلي', false, true),
('IT', 'Italian', 'إيطالي', false, true),
('JM', 'Jamaican', 'جامايكي', false, true),
('JP', 'Japanese', 'ياباني', false, true),
('JE', 'Jerseyan', 'جيرزي', false, true),
('JO', 'Jordanian', 'أردني', false, true),
('KZ', 'Kazakh', 'كازاخستاني', false, true),
('KE', 'Kenyan', 'كيني', false, true),
('KI', 'I-Kiribati', 'كيريباتي', false, true),
('KP', 'North Korean', 'كوري شمالي', false, true),
('KR', 'South Korean', 'كوري جنوبي', false, true),
('KW', 'Kuwaiti', 'كويتي', false, true),
('KG', 'Kyrgyz', 'قيرغيزستاني', false, true),
('LA', 'Lao', 'لاوسي', false, true),
('LV', 'Latvian', 'لاتفي', false, true),
('LB', 'Lebanese', 'لبناني', false, true),
('LS', 'Mosotho', 'ليسوتي', false, true),
('LR', 'Liberian', 'ليبيري', false, true),
('LY', 'Libyan', 'ليبي', false, true),
('LI', 'Liechtensteiner', 'ليختنشتايني', false, true),
('LT', 'Lithuanian', 'ليتواني', false, true),
('LU', 'Luxembourger', 'لوكسمبورغي', false, true),
('MO', 'Macanese', 'ماكاوي', false, true),
('MG', 'Malagasy', 'مدغشقري', false, true),
('MW', 'Malawian', 'مالاوي', false, true),
('MY', 'Malaysian', 'ماليزي', false, true),
('MV', 'Maldivian', 'مالديفي', false, true),
('ML', 'Malian', 'مالي', false, true),
('MT', 'Maltese', 'مالطي', false, true),
('MH', 'Marshallese', 'مارشالي', false, true),
('MQ', 'Martiniquais', 'مارتينيكي', false, true),
('MR', 'Mauritanian', 'موريتاني', false, true),
('MU', 'Mauritian', 'موريشي', false, true),
('YT', 'Mahoran', 'مايوتي', false, true),
('MX', 'Mexican', 'مكسيكي', false, true),
('FM', 'Micronesian', 'ميكرونيزي', false, true),
('MD', 'Moldovan', 'مولدوفي', false, true),
('MC', 'Monegasque', 'موناكوي', false, true),
('MN', 'Mongolian', 'منغولي', false, true),
('ME', 'Montenegrin', 'مونتينيغري', false, true),
('MS', 'Montserratian', 'مونتسراتي', false, true),
('MA', 'Moroccan', 'مغربي', false, true),
('MZ', 'Mozambican', 'موزمبيقي', false, true),
('MM', 'Myanmar', 'ميانماري', false, true),
('NA', 'Namibian', 'ناميبي', false, true),
('NR', 'Nauruan', 'ناوروي', false, true),
('NP', 'Nepalese', 'نيبالي', false, true),
('NL', 'Dutch', 'هولندي', false, true),
('NC', 'New Caledonian', 'كاليدوني جديد', false, true),
('NZ', 'New Zealander', 'نيوزيلندي', false, true),
('NI', 'Nicaraguan', 'نيكاراغوي', false, true),
('NE', 'Nigerien', 'نيجري', false, true),
('NG', 'Nigerian', 'نيجيري', false, true),
('NU', 'Niuean', 'نييوي', false, true),
('NF', 'Norfolk Islander', 'نورفولكي', false, true),
('MP', 'Northern Marianan', 'مارياني شمالي', false, true),
('NO', 'Norwegian', 'نرويجي', false, true),
('OM', 'Omani', 'عماني', false, true),
('PK', 'Pakistani', 'باكستاني', false, true),
('PW', 'Palauan', 'بالاوي', false, true),
('PS', 'Palestinian', 'فلسطيني', false, true),
('PA', 'Panamanian', 'بنمي', false, true),
('PG', 'Papua New Guinean', 'بابوا غيني', false, true),
('PY', 'Paraguayan', 'باراغواياني', false, true),
('PE', 'Peruvian', 'بيروفي', false, true),
('PH', 'Filipino', 'فلبيني', false, true),
('PN', 'Pitcairn Islander', 'بيتكيرني', false, true),
('PL', 'Polish', 'بولندي', false, true),
('PT', 'Portuguese', 'برتغالي', false, true),
('PR', 'Puerto Rican', 'بورتوريكي', false, true),
('QA', 'Qatari', 'قطري', false, true),
('RE', 'Reunionese', 'ريونيوني', false, true),
('RO', 'Romanian', 'روماني', false, true),
('RU', 'Russian', 'روسي', false, true),
('RW', 'Rwandan', 'رواندي', false, true),
('BL', 'Saint Barthelemy', 'سان بارتيليمي', false, true),
('SH', 'Saint Helenian', 'سانت هيليني', false, true),
('KN', 'Kittitian and Nevisian', 'من سانت كيتس ونيفيس', false, true),
('LC', 'Saint Lucian', 'سانت لوسي', false, true),
('MF', 'Saint Martin', 'سانت مارتيني', false, true),
('PM', 'Saint-Pierrais and Miquelonnais', 'سان بيير وميكلوني', false, true),
('VC', 'Vincentian', 'فنسنتي', false, true),
('WS', 'Samoan', 'سامواي', false, true),
('SM', 'Sammarinese', 'سان ماريني', false, true),
('ST', 'Sao Tomean', 'ساوتومي', false, true),
('SA', 'Saudi', 'سعودي', false, true),
('SN', 'Senegalese', 'سنغالي', false, true),
('RS', 'Serbian', 'صربي', false, true),
('SC', 'Seychellois', 'سيشيلي', false, true),
('SL', 'Sierra Leonean', 'سيراليوني', false, true),
('SG', 'Singaporean', 'سنغافوري', false, true),
('SX', 'Sint Maarten', 'سينت مارتني', false, true),
('SK', 'Slovak', 'سلوفاكي', false, true),
('SI', 'Slovene', 'سلوفيني', false, true),
('SB', 'Solomon Islander', 'من جزر سليمان', false, true),
('SO', 'Somali', 'صومالي', false, true),
('ZA', 'South African', 'جنوب أفريقي', false, true),
('GS', 'South Georgian', 'جورجي جنوبي', false, true),
('SS', 'South Sudanese', 'جنوب سوداني', false, true),
('ES', 'Spanish', 'إسباني', false, true),
('LK', 'Sri Lankan', 'سريلانكي', false, true),
('SD', 'Sudanese', 'سوداني', false, true),
('SR', 'Surinamese', 'سورينامي', false, true),
('SJ', 'Svalbard and Jan Mayen', 'من سفالبارد ويان ماين', false, true),
('SE', 'Swedish', 'سويدي', false, true),
('CH', 'Swiss', 'سويسري', false, true),
('SY', 'Syrian', 'سوري', false, true),
('TW', 'Taiwanese', 'تايواني', false, true),
('TJ', 'Tajik', 'طاجيكستاني', false, true),
('TZ', 'Tanzanian', 'تنزاني', false, true),
('TH', 'Thai', 'تايلندي', false, true),
('TL', 'Timorese', 'تيموري شرقي', false, true),
('TG', 'Togolese', 'توغولي', false, true),
('TK', 'Tokelauan', 'توكيلاوي', false, true),
('TO', 'Tongan', 'تونغي', false, true),
('TT', 'Trinidadian and Tobagonian', 'ترينيدادي وتوباغوني', false, true),
('TN', 'Tunisian', 'تونسي', false, true),
('TR', 'Turkish', 'تركي', false, true),
('TM', 'Turkmen', 'تركمانستاني', false, true),
('TC', 'Turks and Caicos Islander', 'من جزر تركس وكايكوس', false, true),
('TV', 'Tuvaluan', 'توفالوي', false, true),
('UG', 'Ugandan', 'أوغندي', false, true),
('UA', 'Ukrainian', 'أوكراني', false, true),
('AE', 'Emirati', 'إماراتي', false, true),
('GB', 'British', 'بريطاني', false, true),
('US', 'American', 'أمريكي', false, true),
('UM', 'U.S. Islander', 'من جزر الولايات المتحدة النائية', false, true),
('UY', 'Uruguayan', 'أوروغواياني', false, true),
('UZ', 'Uzbek', 'أوزبكستاني', false, true),
('VU', 'Ni-Vanuatu', 'فانواتوي', false, true),
('VE', 'Venezuelan', 'فنزويلي', false, true),
('VN', 'Vietnamese', 'فيتنامي', false, true),
('VG', 'British Virgin Islander', 'من جزر العذراء البريطانية', false, true),
('VI', 'U.S. Virgin Islander', 'من جزر العذراء الأمريكية', false, true),
('WF', 'Wallis and Futuna', 'من واليس وفوتونا', false, true),
('EH', 'Western Saharan', 'صحراوي غربي', false, true),
('YE', 'Yemeni', 'يمني', false, true),
('ZM', 'Zambian', 'زامبي', false, true),
('ZW', 'Zimbabwean', 'زيمبابوي', false, true)
ON CONFLICT (code) DO UPDATE
SET name_en = EXCLUDED.name_en,
    name_ar = EXCLUDED.name_ar,
    active = EXCLUDED.active,
    deleted = EXCLUDED.deleted;