-- 1️⃣ Create country lookup table
CREATE TABLE country (
    id BIGSERIAL PRIMARY KEY,
    code VARCHAR(5) NOT NULL UNIQUE,
    name_en VARCHAR(150) NOT NULL,
    name_ar VARCHAR(150) NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

-- 2️⃣ Insert all ISO alpha-2 countries/territories
INSERT INTO country (code, name_en, name_ar, deleted, active) VALUES
('AF', 'Afghanistan', 'أفغانستان', false, true),
('AL', 'Albania', 'ألبانيا', false, true),
('DZ', 'Algeria', 'الجزائر', false, true),
('AS', 'American Samoa', 'ساموا الأمريكية', false, true),
('AD', 'Andorra', 'أندورا', false, true),
('AO', 'Angola', 'أنغولا', false, true),
('AI', 'Anguilla', 'أنغيلا', false, true),
('AQ', 'Antarctica', 'القارة القطبية الجنوبية', false, true),
('AG', 'Antigua and Barbuda', 'أنتيغوا وباربودا', false, true),
('AR', 'Argentina', 'الأرجنتين', false, true),
('AM', 'Armenia', 'أرمينيا', false, true),
('AW', 'Aruba', 'أروبا', false, true),
('AU', 'Australia', 'أستراليا', false, true),
('AT', 'Austria', 'النمسا', false, true),
('AZ', 'Azerbaijan', 'أذربيجان', false, true),
('BS', 'Bahamas', 'الباهاماس', false, true),
('BH', 'Bahrain', 'البحرين', false, true),
('BD', 'Bangladesh', 'بنغلاديش', false, true),
('BB', 'Barbados', 'باربادوس', false, true),
('BY', 'Belarus', 'بيلاروس', false, true),
('BE', 'Belgium', 'بلجيكا', false, true),
('BZ', 'Belize', 'بليز', false, true),
('BJ', 'Benin', 'بنين', false, true),
('BM', 'Bermuda', 'برمودا', false, true),
('BT', 'Bhutan', 'بوتان', false, true),
('BO', 'Bolivia (Plurinational State of)', 'بوليفيا', false, true),
('BA', 'Bosnia and Herzegovina', 'البوسنة والهرسك', false, true),
('BW', 'Botswana', 'بتسوانا', false, true),
('BR', 'Brazil', 'البرازيل', false, true),
('BN', 'Brunei Darussalam', 'بروناي', false, true),
('BG', 'Bulgaria', 'بلغاريا', false, true),
('BF', 'Burkina Faso', 'بوركينا فاسو', false, true),
('BI', 'Burundi', 'بوروندي', false, true),
('KH', 'Cambodia', 'كمبوديا', false, true),
('CM', 'Cameroon', 'الكاميرون', false, true),
('CA', 'Canada', 'كندا', false, true),
('CV', 'Cabo Verde', 'الرأس الأخضر', false, true),
('KY', 'Cayman Islands', 'جزر كايمان', false, true),
('CF', 'Central African Republic', 'جمهورية أفريقيا الوسطى', false, true),
('TD', 'Chad', 'تشاد', false, true),
('CL', 'Chile', 'تشيلي', false, true),
('CN', 'China', 'الصين', false, true),
('CX', 'Christmas Island', 'جزيرة الكريسماس', false, true),
('CC', 'Cocos (Keeling) Islands', 'جزر كوكوس', false, true),
('CO', 'Colombia', 'كولومبيا', false, true),
('KM', 'Comoros', 'جزر القمر', false, true),
('CG', 'Congo', 'الكونغو', false, true),
('CD', 'Congo (Democratic Republic of the)', 'جمهورية الكونغو الديمقراطية', false, true),
('CK', 'Cook Islands', 'جزر كوك', false, true),
('CR', 'Costa Rica', 'كوستاريكا', false, true),
('CI', 'Côte d’Ivoire', 'ساحل العاج', false, true),
('HR', 'Croatia', 'كرواتيا', false, true),
('CU', 'Cuba', 'كوبا', false, true),
('CY', 'Cyprus', 'قبرص', false, true),
('CZ', 'Czechia', 'التشيك', false, true),
('DK', 'Denmark', 'الدنمارك', false, true),
('DJ', 'Djibouti', 'جيبوتي', false, true),
('DM', 'Dominica', 'دومينيكا', false, true),
('DO', 'Dominican Republic', 'جمهورية الدومينيكان', false, true),
('EC', 'Ecuador', 'الإكوادور', false, true),
('EG', 'Egypt', 'مصر', false, true),
('SV', 'El Salvador', 'السلفادور', false, true),
('GQ', 'Equatorial Guinea', 'غينيا الاستوائية', false, true),
('ER', 'Eritrea', 'إريتريا', false, true),
('EE', 'Estonia', 'إستونيا', false, true),
('SZ', 'Eswatini', 'إسواتيني', false, true),
('ET', 'Ethiopia', 'إثيوبيا', false, true),
('FK', 'Falkland Islands (Malvinas)', 'جزر فوكلاند', false, true),
('FO', 'Faroe Islands', 'جزر فارو', false, true),
('FJ', 'Fiji', 'فيجي', false, true),
('FI', 'Finland', 'فنلندا', false, true),
('FR', 'France', 'فرنسا', false, true),
('GF', 'French Guiana', 'غيانا الفرنسية', false, true),
('PF', 'French Polynesia', 'بولينيزيا الفرنسية', false, true),
('TF', 'French Southern Territories', 'الأقاليم الجنوبية الفرنسية', false, true),
('GA', 'Gabon', 'الغابون', false, true),
('GM', 'Gambia', 'غامبيا', false, true),
('GE', 'Georgia', 'جورجيا', false, true),
('DE', 'Germany', 'ألمانيا', false, true),
('GH', 'Ghana', 'غانا', false, true),
('GI', 'Gibraltar', 'جبل طارق', false, true),
('GR', 'Greece', 'اليونان', false, true),
('GL', 'Greenland', 'جرينلاند', false, true),
('GD', 'Grenada', 'غرينادا', false, true),
('GP', 'Guadeloupe', 'غوادلوب', false, true),
('GU', 'Guam', 'غوام', false, true),
('GT', 'Guatemala', 'غواتيمالا', false, true),
('GG', 'Guernsey', 'غيرنزي', false, true),
('GN', 'Guinea', 'غينيا', false, true),
('GW', 'Guinea-Bissau', 'غينيا بيساو', false, true),
('GY', 'Guyana', 'غويانا', false, true),
('HT', 'Haiti', 'هايتي', false, true),
('HM', 'Heard Island and McDonald Islands', 'جزيرة هيرد وجزر ماكدونالد', false, true),
('VA', 'Holy See', 'الكرسي الرسولي', false, true),
('HN', 'Honduras', 'هندوراس', false, true),
('HK', 'Hong Kong', 'هونغ كونغ', false, true),
('HU', 'Hungary', 'المجر', false, true),
('IS', 'Iceland', 'آيسلندا', false, true),
('IN', 'India', 'الهند', false, true),
('ID', 'Indonesia', 'إندونيسيا', false, true),
('IR', 'Iran', 'إيران', false, true),
('IQ', 'Iraq', 'العراق', false, true),
('IE', 'Ireland', 'أيرلندا', false, true),
('IL', 'Israel', 'إسرائيل', false, true),
('IT', 'Italy', 'إيطاليا', false, true),
('JM', 'Jamaica', 'جامايكا', false, true),
('JP', 'Japan', 'اليابان', false, true),
('JE', 'Jersey', 'جيرسي', false, true),
('JO', 'Jordan', 'الأردن', false, true),
('KZ', 'Kazakhstan', 'كازاخستان', false, true),
('KE', 'Kenya', 'كينيا', false, true),
('KI', 'Kiribati', 'كيريباتي', false, true),
('KP', 'North Korea', 'كوريا الشمالية', false, true),
('KR', 'South Korea', 'كوريا الجنوبية', false, true),
('KW', 'Kuwait', 'الكويت', false, true),
('KG', 'Kyrgyzstan', 'قيرغيزستان', false, true),
('LA', 'Laos', 'لاوس', false, true),
('LV', 'Latvia', 'لاتفيا', false, true),
('LB', 'Lebanon', 'لبنان', false, true),
('LS', 'Lesotho', 'ليسوتو', false, true),
('LR', 'Liberia', 'ليبيريا', false, true),
('LY', 'Libya', 'ليبيا', false, true),
('LI', 'Liechtenstein', 'ليختنشتاين', false, true),
('LT', 'Lithuania', 'ليتوانيا', false, true),
('LU', 'Luxembourg', 'لوكسمبورغ', false, true),
('MO', 'Macao', 'ماكاو', false, true),
('MG', 'Madagascar', 'مدغشقر', false, true),
('MW', 'Malawi', 'ملاوي', false, true),
('MY', 'Malaysia', 'ماليزيا', false, true),
('MV', 'Maldives', 'جزر المالديف', false, true),
('ML', 'Mali', 'مالي', false, true),
('MT', 'Malta', 'مالطا', false, true),
('MH', 'Marshall Islands', 'جزر مارشال', false, true),
('MQ', 'Martinique', 'مارتينيك', false, true),
('MR', 'Mauritania', 'موريتانيا', false, true),
('MU', 'Mauritius', 'موريشيوس', false, true),
('YT', 'Mayotte', 'مايوت', false, true),
('MX', 'Mexico', 'المكسيك', false, true),
('FM', 'Micronesia (Federated States of)', 'ميكرونيزيا', false, true),
('MD', 'Moldova (Republic of)', 'مولدوفا', false, true),
('MC', 'Monaco', 'موناكو', false, true),
('MN', 'Mongolia', 'منغوليا', false, true),
('ME', 'Montenegro', 'الجبل الأسود', false, true),
('MS', 'Montserrat', 'مونتسيرات', false, true),
('MA', 'Morocco', 'المغرب', false, true),
('MZ', 'Mozambique', 'موزمبيق', false, true),
('MM', 'Myanmar', 'ميانمار', false, true),
('NA', 'Namibia', 'ناميبيا', false, true),
('NR', 'Nauru', 'ناورو', false, true),
('NP', 'Nepal', 'نيبال', false, true),
('NL', 'Netherlands', 'هولندا', false, true),
('NC', 'New Caledonia', 'كاليدونيا الجديدة', false, true),
('NZ', 'New Zealand', 'نيوزيلندا', false, true),
('NI', 'Nicaragua', 'نيكاراغوا', false, true),
('NE', 'Niger', 'النيجر', false, true),
('NG', 'Nigeria', 'نيجيريا', false, true),
('NU', 'Niue', 'نيوي', false, true),
('NF', 'Norfolk Island', 'جزيرة نورفولك', false, true),
('MP', 'Northern Mariana Islands', 'جزر ماريانا الشمالية', false, true),
('NO', 'Norway', 'النرويج', false, true),
('OM', 'Oman', 'عمان', false, true),
('PK', 'Pakistan', 'باكستان', false, true),
('PW', 'Palau', 'بالاو', false, true),
('PS', 'Palestine, State of', 'فلسطين', false, true),
('PA', 'Panama', 'بنما', false, true),
('PG', 'Papua New Guinea', 'بابوا غينيا الجديدة', false, true),
('PY', 'Paraguay', 'باراغواي', false, true),
('PE', 'Peru', 'بيرو', false, true),
('PH', 'Philippines', 'الفلبين', false, true),
('PN', 'Pitcairn', 'بتكايرن', false, true),
('PL', 'Poland', 'بولندا', false, true),
('PT', 'Portugal', 'البرتغال', false, true),
('PR', 'Puerto Rico', 'بورتو ريكو', false, true),
('QA', 'Qatar', 'قطر', false, true),
('RE', 'Réunion', 'ريونيون', false, true),
('RO', 'Romania', 'رومانيا', false, true),
('RU', 'Russian Federation', 'روسيا', false, true),
('RW', 'Rwanda', 'رواندا', false, true),
('BL', 'Saint Barthélemy', 'سان بارتيلمي', false, true),
('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'سانت هيلينا', false, true),
('KN', 'Saint Kitts and Nevis', 'سانت كيتس ونيفيس', false, true),
('LC', 'Saint Lucia', 'سانت لوسيا', false, true),
('MF', 'Saint Martin (French part)', 'سانت مارتن', false, true),
('PM', 'Saint Pierre and Miquelon', 'سانت بيير وميكلون', false, true),
('VC', 'Saint Vincent and the Grenadines', 'سانت فنسنت وجرينادين', false, true),
('WS', 'Samoa', 'ساموا', false, true),
('SM', 'San Marino', 'سان مارينو', false, true),
('ST', 'Sao Tome and Principe', 'ساو تومي وبرينسيبي', false, true),
('SA', 'Saudi Arabia', 'المملكة العربية السعودية', false, true),
('SN', 'Senegal', 'السنغال', false, true),
('RS', 'Serbia', 'صربيا', false, true),
('SC', 'Seychelles', 'سيشيل', false, true),
('SL', 'Sierra Leone', 'سيراليون', false, true),
('SG', 'Singapore', 'سنغافورة', false, true),
('SX', 'Sint Maarten (Dutch part)', 'سينت مارتن', false, true),
('SK', 'Slovakia', 'سلوفاكيا', false, true),
('SI', 'Slovenia', 'سلوفينيا', false, true),
('SB', 'Solomon Islands', 'جزر سليمان', false, true),
('SO', 'Somalia', 'الصومال', false, true),
('ZA', 'South Africa', 'جنوب أفريقيا', false, true),
('GS', 'South Georgia and the South Sandwich Islands', 'جورجيا الجنوبية وجزر ساندويتش الجنوبية', false, true),
('SS', 'South Sudan', 'جنوب السودان', false, true),
('ES', 'Spain', 'إسبانيا', false, true),
('LK', 'Sri Lanka', 'سريلانكا', false, true),
('SD', 'Sudan', 'السودان', false, true),
('SR', 'Suriname', 'سورينام', false, true),
('SJ', 'Svalbard and Jan Mayen', 'سفالبارد ويان ماين', false, true),
('SE', 'Sweden', 'السويد', false, true),
('CH', 'Switzerland', 'سويسرا', false, true),
('SY', 'Syrian Arab Republic', 'سوريا', false, true),
('TW', 'Taiwan, Province of China', 'تايوان', false, true),
('TJ', 'Tajikistan', 'طاجيكستان', false, true),
('TZ', 'Tanzania, United Republic of', 'تنزانيا', false, true),
('TH', 'Thailand', 'تايلاند', false, true),
('TL', 'Timor-Leste', 'تيمور الشرقية', false, true),
('TG', 'Togo', 'توغو', false, true),
('TK', 'Tokelau', 'توكيلاو', false, true),
('TO', 'Tonga', 'تونغا', false, true),
('TT', 'Trinidad and Tobago', 'ترينيداد وتوباغو', false, true),
('TN', 'Tunisia', 'تونس', false, true),
('TR', 'Turkey', 'تركيا', false, true),
('TM', 'Turkmenistan', 'تركمانستان', false, true),
('TC', 'Turks and Caicos Islands', 'جزر تركس وكايكوس', false, true),
('TV', 'Tuvalu', 'توفالو', false, true),
('UG', 'Uganda', 'أوغندا', false, true),
('UA', 'Ukraine', 'أوكرانيا', false, true),
('AE', 'United Arab Emirates', 'الإمارات العربية المتحدة', false, true),
('GB', 'United Kingdom of Great Britain and Northern Ireland', 'المملكة المتحدة', false, true),
('US', 'United States of America', 'الولايات المتحدة', false, true),
('UM', 'United States Minor Outlying Islands', 'جزر الولايات المتحدة النائية', false, true),
('UY', 'Uruguay', 'أوروغواي', false, true),
('UZ', 'Uzbekistan', 'أوزبكستان', false, true),
('VU', 'Vanuatu', 'فانواتو', false, true),
('VE', 'Venezuela (Bolivarian Republic of)', 'فنزويلا', false, true),
('VN', 'Viet Nam', 'فيتنام', false, true),
('VG', 'Virgin Islands (British)', 'جزر فيرجن البريطانية', false, true),
('VI', 'Virgin Islands (U.S.)', 'جزر فيرجن الأمريكية', false, true),
('WF', 'Wallis and Futuna', 'جزر واليس وفوتونا', false, true),
('EH', 'Western Sahara', 'الصحراء الغربية', false, true),
('YE', 'Yemen', 'اليمن', false, true),
('ZM', 'Zambia', 'زامبيا', false, true),
('ZW', 'Zimbabwe', 'زيمبابوي', false, true);
